default_settings: null
behaviors:
  MainImitppo:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0004
      learning_rate_schedule: constant
      batch_size: 500
      buffer_size: 70000
      buffer_init_steps: 3500
      tau: 0.005
      steps_per_update: 12.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 12.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 100
    checkpoint_interval: 100000
    max_steps: 13000000
    time_horizon: 256
    summary_freq: 10000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: cameray-stack2-240135-2
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
